### ISSUE TITLE
Write tests for all components/apps 

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-bio#103]
Now we have integration testing set up, we need a common test suite that is used for all common features and files specific to each component's features. 

@Bachibouzouk has already started on his (#102) for Volcano plot. 

We still need to finish tests for: 
- [x] general (to be used for all components) (#142, #146, #173)
- [ ] Alignment Chart 
- [ ] Circos 
- [x] Ideogram (#182)
- [ ] Molecule3D 
- [x] NeedlePlot (#146) 
- [ ] SequenceViewer 
- [ ] Speck 
- [ ] Clustergram 
- [x] Manhattan plot (#142)
- [x] Volcano plot (#142, #102)
- [ ] Oncoprint (#191, #194)

**Comment by shammamah** [comment]
@mkcor @Bachibouzouk I'm thinking we can split these up. 

@shammamah 
* Speck 
* Sequence viewer 
* Clustergram 

@Bachibouzouk 
* Alignment chart
* Circos 
* Manhattan plot 
* Needle plot

@mkcor 
* Molecule3D
* Oncoprint 
 * Ideogram 

Let me know if you want to switch anything around!

**Comment by Bachibouzouk** [comment]
@shammamah, @mkcor : I made tests for testing the app works correctly as well as tests for testing the passing of props to the component, ping me if you want to chat about the way I carry out the tests.

**Comment by mkcor** [comment]
@Bachibouzouk Wonderful! Do you mean it would be more fruitful to have this chat *before* I review #142 and #143 ?

**Comment by Bachibouzouk** [comment]
Useful command to run only one test `pytest --driver Chrome tests/<test file>::<test function within the file>`

**Comment by Bachibouzouk** [comment]
Useful to check if the react component changed after modifying a prop value
https://selenium-python.readthedocs.io/locating-elements.html#locating-elements-by-class-name

**Comment by mkcor** [comment]
As per today's discussion, we want to make sure we are defensive in our demo apps "and the most common way to do it is to add assertions to our code" (https://swcarpentry.github.io/python-novice-inflammation/08-defensive/index.html).
/cc @shammamah @Bachibouzouk
