### ISSUE TITLE
Why are generated files in the version control?

### ISSUE THREAD

**Issue by emmanuelle** [plotly/dash-bio#116]
I noticed that generated files in dash-bio/dash_bio (such as bundle.js etc.), or the .tar.gz, are versioned in this repository. I wonder why this is the case: usually (at least in my experience) files which can be generated are not integrated in the version control, in particular for large files.

**Comment by chriddyp** [comment]
> Was wondering if you saw any advantages that you can share with us in favour of keeping those files in version control?

While unconventional, we keep the generated files in source control across all our dash projects for several reasons:
1. It allows community members to clone the repo (or a branch) to try things out immediately. No build step required (many of our community members have never used npm)
2. It makes it easier for us to use heroku and DDS review apps: there is no intermediate built step required.
3. It ensures that the builds that the devs are creating _work correctly_. This is just another level of sanity checks. If the builds were created by machines (e.g. heroku while creating a review app), then we wouldn't be sanity checking the builds that _we're creating_ (and therefore ultimately publishing).
4. It ensures that what is in the repo is what is actually published to pypi and npm. If someone is in `master` and creates the build files, `git status` should return nothing. This allows us to give many people publishing rights and helps ensure that we aren't publishing something misconfigured. There is also an extra sanity check: any developer should be able to checkout master, `npm i`, create the build and check that their build doesn't produce any git diffs. If it does produce git diffs, then someone's environment is locked down correctly.
5. It's easier to roll back to different versions with git tags, as the historical builds are always available.
6. Other package systems, like `conda`, apparently rely on git tags for creating the releases.


This is at the expense of frequent merge conflicts. However, these merge conflicts are really easy to resolve: just fix `src` and re-run the builds (you don't need to manually inspect / correct the artifacts).

**Comment by T4rk1n** [comment]
It also allows for installing from git and serving the bundles locally, otherwise the bundles are not found.

**Comment by alexcjohnson** [comment]
This is a much wider discussion than just dash-bio - let's continue at https://github.com/plotly/dash-core/issues/36
