### ISSUE TITLE
File names in `tests/dash/sample_data` should bear the app name as a convention

### ISSUE THREAD

**Issue by Bachibouzouk** [plotly/dash-bio#117]
This would help sort out which ones are needed and which ones we could erase as well

**Comment by shammamah** [comment]
We'd have to go through all of the demo apps and change the paths when they open the files -- @Bachibouzouk would you be able to do this (with the refactoring you mentioned in PyCharm)?

**Comment by shammamah** [comment]
Yep definitely!
