### ISSUE TITLE
When writing tests in the tests package, if one import dash there is an ambiguity between Plotly's dash and tests/dash package inside dash-bio repo.

### ISSUE THREAD

**Issue by Bachibouzouk** [plotly/dash-bio#124]
I propose to change name of `tests/dash` package to `tests/dash_demo_apps`

**Comment by Bachibouzouk** [comment]
> How about just `demo_apps` then (shorter)?

@mkcor : I agree, @shammamah are you ok with it too?

**Comment by shammamah** [comment]
@Bachibouzouk @mkcor Could we maybe add in the name of the package too? like `tests/dashbio_demos`?
