### ISSUE TITLE
Alignment viewer: Issues with sync between subplots

### ISSUE THREAD

**Issue by jackparmer** [plotly/dash-bio#159]
- [ ] If you zoom into the **center heatmap**, the viewport of the **bottom global view**  doesn't always update.
- [ ] When you are very zoomed into the **main heatmap**, if you click-drag on the **bottom global view**, only the x-axis labels of the **center heatmap** update.

![image](https://user-images.githubusercontent.com/1865834/52440361-ed64d400-2aeb-11e9-8809-e74ca22290fd.png)

I thought this might be a plotly.js issue, but I don't get this off synch behavior in Chart Studio: https://plot.ly/~jackp/18501/#/

So I wonder if this app is using an older version of plotly.js.

The JS console is full of these bundle.js errors from click-dragging. I see `calcdata` in the compressed source, so it does seem plotly.js is having trouble in this particular environment.

![image](https://user-images.githubusercontent.com/1865834/52440916-4e40dc00-2aed-11e9-93ef-19c97b76180f.png)

**Comment by jackluo** [comment]
Difference between here and on Chart Studio is that drag is manually handled on MSA
Seems like its the same bug I previously mentionned: https://github.com/plotly/plotly.js/issues/3305

I'll make a local copy of the React code inside the Dash component instead of just wrapping the imported react-alignment-viewer for now if we can't get a quick solution before release, thoughts

**Comment by etpinard** [comment]
@jackluo I'm curious. What makes you so sure that https://github.com/plotly/plotly.js/issues/3305 is at the root of the problem?

**Comment by jackluo** [comment]
@etpinard zoom causes work when its the drag zoom tool, but + - works fine 
Seems like onRelayout events don't always get triggered either, can be confirmed by console logging

**Comment by etpinard** [comment]
Ok, and what is the app suppose to do on drag?

**Comment by jackluo** [comment]
Both the heatmap and webgl text overlay should drag/zoom together

**Comment by etpinard** [comment]
OK now, why do need an on-relayout hanlder?

https://plot.ly/~jackp/18501/#/ has a shared x-axis, and seems to zoom/pan properly.

Moreover, are you using subplots are multiple graph divs in your app? If you're using multiple graph divs, then you should not encounter https://github.com/plotly/plotly.js/issues/3305

**Comment by jackparmer** [comment]
FWIW, https://plot.ly/~jackp/18501/#/ is exported directly into Chart
Studio from Jack Luo's Dash app. I didn't make any further modifications.
JL's Dash app is not using multiple graph divs. You can inspect it here:
https://dash-bio.plotly.host/dash-alignment-viewer/

**Comment by etpinard** [comment]
Is there an easy way to try a new plotly.js bundle in a dash app?

If so, could something try (or tell me how to do it) this bundle -> https://31572-45646037-gh.circle-artifacts.com/0/dist/plotly.min.js ? I think it might solve the syncing problems presented here.
