### ISSUE TITLE
Manhattan: Loading bar after changing thresholds

### ISSUE THREAD

**Issue by jackparmer** [plotly/dash-bio#163]
It takes a second for the plot to redraw after the threshold value on the slider changes. It would be nice if a loading spinner or "Loading..." text popped up during this wait time. I assumed it was broken at first. I would also suggest using `scattergl` instead of SVG - the plotting time should be faster.

Could collaborate with https://github.com/plotly/dash-bio/issues/160

I believe that DDK might have a loading bar solution.

**Comment by Bachibouzouk** [comment]
@jackparmer : it is already a `plotly.graph_objs.Scattergl`. I don't think it is the plotting which takes time to render. I think it is the computation to prepare the data to plot from the raw dataset which takes some time.

**Comment by jackparmer** [comment]
> it is already a `plotly.graph_objs.Scattergl`

I see, I forgot that the plotly.js webgl axes are now SVG.

**Comment by shammamah** [comment]
Moved to #213.
