### ISSUE TITLE
Dash Needle Plot: Reset plot viewing window on dataset change

### ISSUE THREAD

**Issue by jackparmer** [plotly/dash-bio#164]
When changing a dataset, the zoom window at the bottom of the plot should also reset to view the entire x axis.

![image](https://user-images.githubusercontent.com/1865834/52442337-d7a5dd80-2af0-11e9-80f2-bddba2364bee.png)

**Comment by Bachibouzouk** [comment]
`xStart` and `xStop` are part of the state of the component, they are set to `null` by default. I guess this has to be modified in `componentWillReceiveProps` if the `mutationData` prop changes.

**Comment by jackluo** [comment]
@jackparmer @Bachibouzouk i encountered the same issue 1 month ago while doing alignment viewer 

@Bachibouzouk  can fix this for you + add event/click/hover interactivity if you like

**Comment by Bachibouzouk** [comment]
> @Bachibouzouk can fix this for you + add event/click/hover interactivity if you like

@jackluo yes I would like :)

**Comment by jackluo** [comment]
Will do
