### ISSUE TITLE
Dash Volcano Plot: Limit range of input values

### ISSUE THREAD

**Issue by jackparmer** [plotly/dash-bio#165]
Could use a slider or a dial from Dash DAQ for example to limit the range to threshold and effect size values that make sense. If using Dash DAQ, could also use color picker for the highlight color. 

![image](https://user-images.githubusercontent.com/1865834/52442507-4c791780-2af1-11e9-8060-12748b57006e.png)

It also wasn't clear to me that these were outputs versus inputs:

![image](https://user-images.githubusercontent.com/1865834/52442559-70d4f400-2af1-11e9-97c0-a071e5d57876.png)

**Comment by mkcor** [comment]
FYI taking over the PR today so we can ship @Bachibouzouk's work ASAP!
