### ISSUE TITLE
Topbar design 

### ISSUE THREAD

**Issue by jackparmer** [plotly/dash-bio#166]
From @jackluo on Slack

> can we reduce the height of the navbar from 100px to 60px? would be great from ux perspective

> also add an "view on github" text next to GH icon

**Comment by angeladaodao** [comment]
Does it looks okay for you?

<img width="1026" alt="screen shot 2019-02-08 at 2 53 14 pm" src="https://user-images.githubusercontent.com/37411533/52502714-742fb480-2bb1-11e9-9e07-1cedf772bbc4.png">
