### ISSUE TITLE
Transform gallery template into standalone package?

### ISSUE THREAD

**Issue by emmanuelle** [plotly/dash-bio#168]
The layout of the dash-bio gallery is very nice and other projects could reuse it. Is there a plan to have a standalone module / package for creating a gallery (say, one could import a function ``create_gallery`` which would take as arguments paths for apps and thumbnails, plus optional parameters as keyword arguments)? Sorry if this already exists :-).

**Comment by emmanuelle** [comment]
I'm interested in having a similar gallery for the dash-canvas project, and I wonder whether there is a better solution than copy/pasting the code of the dash-bio gallery...

**Comment by T4rk1n** [comment]
Look into https://github.com/audreyr/cookiecutter

The component boilerplate use it. https://github.com/plotly/dash-component-boilerplate

**Comment by emmanuelle** [comment]
Thanks for your answer @T4rk1n. Indeed, it would be possible to have a cookiecutter repo with the index.py and a few other files maybe. But wouldn't it be easier (and more classical) for developers to install a python package and import a function from it? Maybe I'm missing something and it's not easy do return suitable objects from a function in a module, I haven't thought enough about it.

**Comment by T4rk1n** [comment]
Maybe I miserunderstood what you wanted to do. Your python function would generate a project template ? Or is it create a gallery app with multiple apps and thumbnails images in a directory ? If the later I would create a function. I had a similar idea for pytest-dash, https://github.com/T4rk1n/pytest-dash/issues/24

**Comment by jackparmer** [comment]
> The layout of the dash-bio gallery is very nice and other projects could reuse it. Is there a plan to have a standalone module / package for creating a gallery

We're just using DDS servers now and the default app gallery that ships with them (the "portal"). I think that the Dash Canvas examples should go on the [Dash Bio DDS / Portal](https://dash-bio.plotly.host/Portal/), since they all use life science images. Sham can show you how to deploy these apps to the DDS portal whenever you're interested in doing so.
