### ISSUE TITLE
Nested props of component don't have default values as defined in .react.js file

### ISSUE THREAD

**Issue by Bachibouzouk** [plotly/dash-bio#174]
if there are default values defined in the `defaultProps` of the .react.js file, they are not accessible through `dash.dependencies.Input` or `dash.dependencies.State` 

```
COMPONENT.propTypes = {
     givenProp: PropTypes.shape({
          subprop1: PropTypes.string,
          subprop2: PropTypes.int,
     })
};

COMPONENT.defaultProps = {
      givenProp: {
           subprop1: "a string",
           subprop2: 12
      }
};
```

If one define a callback like this one
```
@app.callback(
        Output(), # not relevant for the example
        [Input()], # not relevant fot the example
        [State('COMPONENT', 'givenProp')]
):
def do_something(_, prop):
    # here 'prop' will by default be equal to None instead of {subprop1: "a_string", subprop2: 12}
```

This is probably due to the nested props. Also if one try to assign a dict with `subprop3` as a key to `givenProp` via a callback, it doesn't generate a `dash.exceptions.NonExistentPropException`.

**Comment by Bachibouzouk** [comment]
@shammamah - maybe this issue should be moved to dash as it seems a more general case?

**Comment by shammamah** [comment]
Agreed! Please refer back to this issue before closing it :)
