### ISSUE TITLE
Move AlignmentViewer, AlignmentChart and OncoPrint into dash-bio repo

### ISSUE THREAD

**Issue by Bachibouzouk** [plotly/dash-bio#179]
Currently they live in https://github.com/plotly/react-oncoprint and https://github.com/plotly/react-alignment-viewer and get imported from the .react.js files.

List of move to perform
- [ ] OncoPrint
- [ ] AlignmentViewer

**Comment by jackluo** [comment]
@Bachibouzouk hey pierre, they currenty live independently for js users to use, same with https://github.com/plotly/react-genome-viewer

We could maintain 2 separate versions but the I think philosophy is like with circos.js etc - the dash versions should just be wrappers around the main react components

**Comment by shammamah** [comment]
@Bachibouzouk - @jackluo makes a good point here -- there might be lots of JS users who want to use this component as well. Closing the issue now!
