### ISSUE TITLE
Update to pytest-dash v2.0.0

### ISSUE THREAD

**Issue by T4rk1n** [plotly/dash-bio#180]
Main breaking change is the removal of `pytest-selenium` support, the selenium driver is now included on the [`dash_threaded`/`dash_subprocess` fixtures](https://pytest-dash.readthedocs.io/en/latest/usage.html#dash-threaded-example). The `--driver` argument is now `--webdriver`, you can set in `pytest.ini` config file.

**Comment by Bachibouzouk** [comment]
If I change `--driver` to `--webdriver`, I get a `pytest` error : `_pytest.config.exceptions.UsageError: --driver must be specified`

**Comment by T4rk1n** [comment]
@Bachibouzouk The `driver` argument is for `pytest-selenium`, pytest-dash no longer uses pytest-selenium and instead provide the selenium driver directly on the fixture: eg `dash_threaded.driver`.
