### ISSUE TITLE
Ideogram component have props which are not dash props

### ISSUE THREAD

**Issue by Bachibouzouk** [plotly/dash-bio#186]
Some props cannot be updated via a callback, they are 'read only props':
I found that for `brushData` :
https://github.com/plotly/dash-bio/blob/eb46d27164a134daf7a5dbb25335d7777f7c9ff6/src/lib/components/Ideogram.react.js#L404

This other prop, `brush` cannot be used in a callback without also defining a callback on the `chromosome` prop. It should be clearly indicated that one cannot use these props as standard dash-props.
https://github.com/plotly/dash-bio/blob/eb46d27164a134daf7a5dbb25335d7777f7c9ff6/src/lib/components/Ideogram.react.js#L392

**Comment by shammamah** [comment]
Closing this, as the main concern ("It should be clearly indicated that one cannot use these props as standard dash-props.") appears to have been addressed in the additions to the Ideogram docstrings in #182.
