### ISSUE TITLE
Setup install requirements include libraries only used in utils folder

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-bio#196]
Related discussion: #195 

Should we move the `utils` folder to its own "side" package? Not everyone will be using the parsers that we have provided, and this might result in them installing packages they don't need along with Dash Bio.

**Comment by shammamah** [comment]
@mkcor @Bachibouzouk Any thoughts on this?

**Comment by Bachibouzouk** [comment]
@shammamah how would you name it then ? `dash_bio_utils` ?

**Comment by shammamah** [comment]
Yeah, I think that would be the way to go if we choose to separate the two.

**Comment by mkcor** [comment]
I concur (always happy to increase modularity). And then we would publish this extra package to PyPI as `dash-bio-utils` and people could `pip install dash-bio-utils`?

**Comment by shammamah** [comment]
That is what I was thinking!

**Comment by mkcor** [comment]
Great! Repeating that I'm all for it. Feel free to assign this task to me, but we might have to do some re-prioritizing.

**Comment by nicolaskruchten** [comment]
My feeling is that we should pull all this stuff out into a separate package such that the Dash components themselves have the smallest dependency footprint possible. My rationale is that the more dependencies you have, the more likely you are to conflict with someone's existing stuff and/or inherit your dependencies' installation headaches. Also it just bloats the install sizes for not much benefit IMO.

**Comment by alexcjohnson** [comment]
@mkcor asked about this on slack, in the context of the `dash`/`dash-renderer` [monorepo](https://github.com/plotly/dash/pull/709) that seems like it's going in the opposite direction. Responding here to be more visible:

The pieces of the `dash` monorepo will still be separate packages on `PyPI` - well, mostly - @byronz and I are discussing making `pytest-dash` into submodule `dash.testing`, but `dash-renderer` and `dash-component-system` will stay separate on `PyPI`. We’re just moving them into a single GH repo to make development easier. The reason for this is that a large fraction of `dash` and `dash-renderer` work is coupled, meaning two cross-referenced PRs (which are hard both to develop and to review), complicated and error-prone merge strategies, and their versions are locked anyway.

Compare that to `dash-core-components`, `dash-html-components`, and `dash-table`, which are staying in their own repos: we do lock versions so you only get the latest versions of these only when you upgrade `dash`, but development tends to be mostly decoupled from `dash` and `dash-renderer` development.

If you expect there will be a lot of cross-package development between `dash-bio` and `dash-bio-utils`, the monorepo pattern can make sense but you can still split them into two PyPI packages. If you think the development will be more or less independent in the two, the separate-repo approach that you've built is simpler and will be easier to maintain.

**Comment by byronz** [comment]
just imagine the future PRs and listen to your heart

**Comment by mkcor** [comment]
@alexcjohnson Thank you so much for clarifying. I think I was entertaining some confusion between Git repo and Python package. It's useful to ponder whether `dash-bio` and `dash-bio-utils` will have coupled developments; I think they will remain fairly decoupled and @shammamah would probably agree.

Thanks for sharing the vision for refactoring `pytest-dash` as well (thanks @byronz for the related private communication).
