### ISSUE TITLE
Circos unicode character leads to errors with Python 2.7

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-bio#205]
While writing documentation for the Dash Bio components, I ran into an issue that involved this specific unicode character: https://www.fileformat.info/info/unicode/char/27a4/index.htm

This is only used in the Circos file (e.g., [here](https://github.com/plotly/dash-bio/blob/0214fb0d9335b387639d3a1b6e8fd8906cb065ed/src/lib/components/Circos.react.js#L145)), and doesn't appear to be super important. 

I have since re-built `dash-bio` temporarily as an [`rc` release](https://test.pypi.org/project/dash-bio/0.0.5rc1/) after removing the character, and the docs (as well as Python 2.7) are cooperating with it, so all we really need to do is change that single character.

**Comment by mkcor** [comment]
You don't want to run Python 2.7 (https://pythonclock.org/).

**Comment by shammamah** [comment]
@mkcor Please see https://github.com/plotly/dash-bio/pull/206#issuecomment-467461440!
