### ISSUE TITLE
[App QA] Mol3d

### ISSUE THREAD

**Issue by jackparmer** [plotly/dash-bio#208]
- [x] The canvas where the molecule is drawn could be wider (ideally full bleed)

- [x] The side bar is cut off vertically - should stretch to the bottom of the page

![image](https://user-images.githubusercontent.com/1865834/53458349-b5262680-3a03-11e9-9974-fbd0849883fd.png)

![image](https://user-images.githubusercontent.com/1865834/53458381-e141a780-3a03-11e9-8230-6ae555a5051a.png)

![image](https://user-images.githubusercontent.com/1865834/53516125-91adbb00-3a99-11e9-9535-b1d1260e446d.png)

- [x] Would be nice to use some color pickers here and redo this UI. I couldn't get this UI to work.

![image](https://user-images.githubusercontent.com/1865834/53458362-c111e880-3a03-11e9-87dc-29cff757c525.png)

- [x] The selection data is super cool but pretty hard to read. Would be nice to pretty print and syntax highlight it. 

![image](https://user-images.githubusercontent.com/1865834/53458373-d555e580-3a03-11e9-848c-5fcefd753670.png)

**Comment by shammamah** [comment]
@jackparmer Instead of making it full-bleed, I made the design follow the general design language @angeladaodao has been giving us. The app is here: https://dash-bio-test-pr-216.herokuapp.com/dash-bio/molecule3d

**Comment by angeladaodao** [comment]
The layout is much more better. Do you want me to give you a set of colors to make it looks even better?

**Comment by jackparmer** [comment]
Beauty! So much better.

**Comment by shammamah** [comment]
@angeladaodao Yes please! Just the color codes would be fine.
