### ISSUE TITLE
Default props of React components don't end up in Python class.

### ISSUE THREAD

**Issue by mkcor** [plotly/dash-bio#214]
Related to #174 

Hi @shammamah,

When writing tests for the OncoPrint component, I've noticed that the 'simple app' launched by Selenium didn't have the same defaults as those specified in OncoPrint (`src/lib/components/OncoPrint.react.js`) and as seen in the demo app (`tests/dashbio_demos/app_onco_print.py`). Specifically, I'm referring to prop `showoverview`, for which the default value is `True` (which seems to correspond to using `Layout(xaxis=dict(rangeslider={'autorange': True}))` in a Plotly plot).

Here's a screenshot of the 'simple app', as used in CI tests:
![still_no_overview](https://user-images.githubusercontent.com/2227806/53559866-6be0ee80-3b4b-11e9-813d-64096469c5a3.png)
as opposed to the demo app:
![overview](https://user-images.githubusercontent.com/2227806/53559906-85823600-3b4b-11e9-825d-f4777d01ec76.png)

As I dug deeper, I noticed that the `OncoPrint` class of the `dash_bio` package did not contain this piece of information (actually, parameter `showoverview=Component.UNDEFINED` and is optional). More generally, components which result from compiling React components into Python don't seem to contain any information about default props...

In the demo app, `showoverview=True` is passed [explicitly](https://github.com/plotly/dash-bio/blob/d628310e143ebaaec2b0cd7cda49bd4cbc511cc5/tests/dashbio_demos/app_onco_print.py#L193), it's not inherited in any way from the OncoPrint component... So, it looks like the whole `defaultProps` part from React components might be lost in translation when compiling into Python.

Maybe it doesn't make that much sense to have these `defaultProps` in the first place?...

**Comment by shammamah** [comment]
>parameter `showoverview=Component.UNDEFINED` and is optional

Yeah, that's confused me in the past too! The default props are set when the components render in the browser, since they're only specified on the React side. The components effectively should behave as though the props are set in Python. 

Could you try deleting the default value of `True` from the toggle that shows the overview in the demo app, and seeing if that causes the same problem? And in the simple testing app, could you inspect the component and set a breakpoint before it renders to see what the props are?

**Comment by shammamah** [comment]
(I actually think I remember having a discussion about this a while ago. Looks like this right here is the culprit: 

https://github.com/plotly/dash/blob/2a4c63ed6215973ca34262c61d6ce25947cf3643/dash/development/_py_components_generation.py#L93

I think `UNDEFINED` in this context has a slightly different meaning -- it seems to mean that the prop/parameter *is permitted to* be undefined. Definitely a little misleading!

**Comment by mkcor** [comment]
> That being said, this behaviour is definitely strange since default props have worked for many other components.

Do we know for sure? My understanding so far is that, for example, `showlegend=True` works well as a default not because it has propagated properly from React to Python, but because it happens to be the default in Plotly...

**Comment by shammamah** [comment]
Yep, this is the case for my SequenceViewer component at the very least, which is a React component.

**Comment by mkcor** [comment]
> Could you try deleting the default value of `True` from the toggle that shows the overview in the demo app, and seeing if that causes the same problem?

I tried this and didn't like what I found... When running the demo app standalone (`$ python tests/dashbio_demos/app_onco_print.py`), I'm seeing what could be expected naively, i.e.:
![standalone_onco](https://user-images.githubusercontent.com/2227806/53581955-d9f2d900-3b7e-11e9-8e0c-0be6bf811846.png)
becomes
![standalone_onco_nodef](https://user-images.githubusercontent.com/2227806/53581977-e37c4100-3b7e-11e9-8b94-50b730cb6911.png)
when I comment out [value=True](https://github.com/plotly/dash-bio/blob/d628310e143ebaaec2b0cd7cda49bd4cbc511cc5/tests/dashbio_demos/app_onco_print.py#L193). So we're losing the overview (we can see there are also CSS/rendering, unrelated issues).

When accessing the demo app from the multipage version (`$ python index.py`), the overview (think Plotly's `layout.xaxis.rangeslider`) is there(?!?), which would back what you just said:

> Yep, this is the case for my SequenceViewer component at the very least, which is a React component.

It's just that the radio button isn't checked upon launching the app:
![multipage_onco_nodef](https://user-images.githubusercontent.com/2227806/53582331-8cc33700-3b7f-11e9-9cd3-583c698d9a40.png)

**Comment by mkcor** [comment]
> And in the simple testing app, could you inspect the component and set a breakpoint before it renders to see what the props are?

Yes, I have, and I'm not finding any default props... I have set the breakpoint right after this line:
https://github.com/plotly/dash-bio/blob/d628310e143ebaaec2b0cd7cda49bd4cbc511cc5/tests/test_common_features.py#L100
and here are the objects:
```py
ipdb> dir()                                                                                                 
['app_name', 'component', 'component_base', 'component_class', 'component_id', 'ipdb', 'kwargs']
ipdb> kwargs.keys()                                                                                         
dict_keys(['data'])
ipdb> component                                                                                             
OncoPrint(id='test-onco-print-component', data=[{'sample': 'TCGA-25-2392-01', 'gene': 'TP53', 'alteration': 'FUSION', 'type': 'FUSION'}, {'sample': 'TCGA-25-2393-01', 'gene': 'TP53', 'alteration': 'FUSION', 'type': 'FUSION'}, {'sample': 'TCGA-04-1331-01', 'gene': 'PTEN', 'alteration': 'HOMDEL', 'type': 'CNA'}, {'sample': 'TCGA-04-1365-01', 'gene': 'PTEN', 'alteration': 'HOMDEL', 'type': 'CNA'}, {'sample': 'TCGA-04-1648-01', 'gene': 'TP53', 'alteration': 'HOMDEL', 'type': 'CNA'}, {'sample': 'TCGA-09-1666-01', 'gene': 'PTEN', 'alteration': 'AMP', 'type': 'CNA'}, {'sample': 'TCGA-13-0720-01', 'gene': 'PTEN', 'alteration': 'HOMDEL', 'type': 'CNA'}, {'sample': 'TCGA-13-0801-01', 'gene': 'BRCA1', 'alteration': 'HOMDEL', 'type': 'CNA'}, {'sample': 'TCGA-13-0801-01', 'gene': 'PTEN', 'alteration': 'HOMDEL', 'type': 'CNA'}, {'sample': 'TCGA-13-0905-01', 'gene': 'PTEN', 'alteration': 'HOMDEL', 'type': 'CNA'}, {'sample': 'TCGA-13-0924-01', 'gene': 'PTEN', 'alteration': 'HOMDEL', 'type': 'CNA'}, {'sample': 'TCGA-13-1405-01', 'gene': 'PTEN', 'alteration': 'HOMDEL', 'type': 'CNA'}, {'sample': 'TCGA-13-1408-01', 'gene': 'TP53', 'alteration': 'HOMDEL', 'type': 'CNA'}, {'sample': 'TCGA-13-1488-01', 'gene': 'PTEN', 'alteration': 'HOMDEL', 'type': 'CNA'}, {'sample': 'TCGA-23-1023-01', 'gene': 'PTEN', 'alteration': 'HOMDEL', 'type': 'CNA'}, {'sample': 'TCGA-23-1032-01', 'gene': 'PTEN', 'alteration': 'HOMDEL', 'type': 'CNA'}, {'sample': 'TCGA-23-1107-01', 'gene': 'PTEN', 'alteration': 'HOMDEL', 'type': 'CNA'}, {'sample': 'TCGA-23-1114-01', 'gene': 'BRCA2', 'alteration': 'HOMDEL', 'type': 'CNA'}, {'sample': 'TCGA-23-1118-01', 'gene': 'PTEN', 'alteration': 'AMP', 'type': 'CNA'}, {'sample': 'TCGA-23-1121-01', 'gene': 'PTEN', 'alteration': 'AMP', 'type': 'CNA'}, {'sample': 'TCGA-23-2084-01', 'gene': 'TP53', 'alteration': 'HOMDEL', 'type': 'CNA'}, {'sample': 'TCGA-24-0968-01', 'gene': 'PTEN', 'alteration': 'HOMDEL', 'type': 'CNA'}, {'sample': 'TCGA-24-0970-01', 'gene': 'BRCA2', 'alteration': 'AMP', 'type': 'CNA'}, {'sample': 'TCGA-24-1103-01', 'gene': 'PTEN', 'alteration': 'HOMDEL', 'type': 'CNA'}, {'sample': 'TCGA-24-1474-01', 'gene': 'TP53', 'alteration': 'AMP', 'type': 'CNA'}, {'sample': 'TCGA-24-1567-01', 'gene': 'PTEN', 'alteration': 'HOMDEL', 'type': 'CNA'}, {'sample': 'TCGA-24-2030-01', 'gene': 'PTEN', 'alteration': 'HOMDEL', 'type': 'CNA'}, {'sample': 'TCGA-24-2036-01', 'gene': 'PTEN', 'alteration': 'HOMDEL', 'type': 'CNA'}, {'sample': 'TCGA-24-2262-01', 'gene': 'PTEN', 'alteration': 'HOMDEL', 'type': 'CNA'}, {'sample': 'TCGA-24-2297-01', 'gene': 'PTEN', 'alteration': 'HOMDEL', 'type': 'CNA'}, {'sample': 'TCGA-25-1322-01', 'gene': 'BRCA2', 'alteration': 'AMP', 'type': 'CNA'}, {'sample': 'TCGA-25-2391-01', 'gene': 'PTEN', 'alteration': 'HOMDEL', 'type': 'CNA'}, {'sample': 'TCGA-25-2401-01', 'gene': 'BRCA2', 'alteration': 'HOMDEL', 'type': 'CNA'}, {'sample': 'TCGA-29-1697-01', 'gene': 'PTEN', 'alteration': 'AMP', 'type': 'CNA'}, {'sample': 'TCGA-29-1702-01', 'gene': 'TP53', 'alteration': 'AMP', 'type': 'CNA'}, {'sample': 'TCGA-29-1761-01', 'gene': 'PTEN', 'alteration': 'HOMDEL', 'type': 'CNA'}])
```
Maybe we could pass other kwargs here:
https://github.com/plotly/dash-bio/blob/61f022057caa2a577387031004e520504e2d35c3/tests/test_onco_print.py#L99
if we wanted to ensure certain props take on certain values, but then that wouldn't be testing defaults...

**Comment by shammamah** [comment]
@mkcor Since this appears to be a problem with OncoPrint only (as far as we know), would you mind changing the title of the issue (or creating a new one)? The default props of *any* React components don't end up in their generated Python classes, but it appears as though OncoPrint specifically has a problem rendering with the default props.

**Comment by mkcor** [comment]
Back when I dug the issue, it actually made sense: That 'default' value was never actually passed, so it couldn't end up in an app (simple version) which doesn't specify it... In this sense, it's not a bug. What I've noticed is that the issue doesn't arise in other cases *only* because the 'default' values in question happen to coincide with defaults in native plotly.
