### ISSUE TITLE
OncoPrint component contains references to (deprecated) events

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-bio#215]
https://github.com/plotly/dash-bio/blob/d628310e143ebaaec2b0cd7cda49bd4cbc511cc5/src/lib/components/OncoPrint.react.js#L38

Doesn't affect functionality, but I think it's a bad idea to keep `fireEvent` anywhere in the component since events are deprecated.

**Comment by mkcor** [comment]
Ok, the issue *title* should be along the lines of: "OncoPrint" component contains references to (deprecated) events" and the suggestion to "remove `fireEvent`" be towards the end of the issue description.
