### ISSUE TITLE
Update package.json modules

### ISSUE THREAD

**Issue by VeraZab** [plotly/dash-bio#240]
Currently, this shows up when running `npm install`:
```
npm WARN react-sequence-viewer@0.2.2 requires a peer of react@^16.0.0 but none is installed. You must install peer dependencies yourself.

audited 27770 packages in 10.078s
found 87 vulnerabilities (1 low, 85 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

Ideally, no vulnerabilities should be found.
But this is hard to achieve as packages and their dependencies are updated daily.

One solution other repos have implemented is the renovate bot.
https://github.com/renovatebot/renovate
@shammamah its a good idea to look into it, and inspire yourself from how its been configured in core-components: https://github.com/plotly/dash-core-components/blob/master/renovate.json

For this one:
`npm WARN react-sequence-viewer@0.2.2 requires a peer of react@^16.0.0 but none is installed. You must install peer dependencies yourself.` it can be ignored if the code works fine. This just means that your project is expecting you to have react 16 installed, but I see that you guys are not at that stage yet. You should update to react 16 when the dash ecosystem is ready for that. React 15 to 16 is a jump with breaking changes. Might require some code rework, and there's lots of blogposts on that. Do not attempt before being sure the dash ecosystem is ready for that jump.

**Comment by mkcor** [comment]
@VeraZab thank you, I've learnt something today! :)
