### ISSUE TITLE
ManhattanPlot is buggy and missing some features

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-bio#246]
The ManhattanPlot app is missing some features of the other apps, such as:

* the option to download a sample dataset/upload a dataset
* multiple datasets to choose from 
* any graph coloring options 

In addition, isolating a trace and subsequently changing the threshold causes all of the traces (including the hidden traces) to display.

**Comment by Bachibouzouk** [comment]
One of the data set of `VolcanoPlot` demo app is shared with `ManhattanPlot` demo app. One could try out the other one with `ManhattanPlot` app as well. I As I don't have a biology background I had a bit of a struggle to find nice looking **and** meaningful data for these plots. I would prefer that someone with biology background undertake that task :)
