### ISSUE TITLE
App QA 2: Circos graph

### ISSUE THREAD

**Issue by jackparmer** [plotly/dash-bio#287]
- [ ] Would be cool if you clicked on chord and it highlighed in black or a contrasting color 
- [ ] Highlighting with checkboxes in Dash Table doesn't seem to be working
- [ ] In general, confusing to figure out how to highlight chords and whether it even works

**Comment by matthewchan15** [comment]
@jackparmer hey I think @shammamah is working on this project at this moment. I haven't touched `dash-bio` since I left.
