### ISSUE TITLE
App QA 2: Molecule viewer

### ISSUE THREAD

**Issue by jackparmer** [plotly/dash-bio#290]
- [x] Some more cool proteins to visualize in sample datasets:
http://pdb101.rcsb.org/motm/231
http://pdb101.rcsb.org/motm/121
http://pdb101.rcsb.org/browse/nucleic-acids
The P53 - https://www.rcsb.org/structure/1uol
- [x] Which DNA and Protein are these
![image](https://user-images.githubusercontent.com/1865834/55284908-fdf83480-534d-11e9-8de9-d8c61b2d8a69.png)
Would be cool to have a description when change in dropdown
- [ ] Check out PyMOL for app ideas and UI
![image](https://user-images.githubusercontent.com/1865834/55284976-78758400-534f-11e9-89da-9a8203e710d2.png)
- PYMOL shows selection at top and uses a table on the right for what you've selected. Black background is nice.

**Comment by shammamah** [comment]
@jackparmer I wanted all of the apps to look similar for consistency. They all have this tabs - component layout. We can change the colours to be more like PyMOL, if that's what @angeladaodao recommends.
