### ISSUE TITLE
Package building isn't part of our CI.

### ISSUE THREAD

**Issue by mkcor** [plotly/dash-bio#300]
Whenever we change JS code, we rebuild the package by running
```bash
npm run build:all
```
which results in `dash_bio/bundle.js`. If this breaks, we have a broken package. Therefore, it is important to make this command part of CI (it's currently [missing](https://github.com/plotly/dash-bio/blob/fc254890310b03502952c6f6c4a430f77538b9bf/.circleci/config.yml#L80) in our CI config).

Not only do we want to double check builds that were successful locally (maybe our dev environments aren't fully up-to-date and/or we don't run both Python 3.6 and Python 3.7), but we also want PRs from the Renovate Bot (dependency updates, such #299 and #284) to go through the full pipeline.

**Comment by shammamah** [comment]
@mkcor Shouldn't it go in the `node` part of the config? https://github.com/plotly/dash-bio/blob/fc254890310b03502952c6f6c4a430f77538b9bf/.circleci/config.yml#L27

**Comment by mkcor** [comment]
Indeed, it's a `node` job:
https://github.com/plotly/dash-bio/blob/fc254890310b03502952c6f6c4a430f77538b9bf/.circleci/config.yml#L94
All I meant was that I went through all the runs and none included package building, i.e., there are no more runs after:
https://github.com/plotly/dash-bio/blob/fc254890310b03502952c6f6c4a430f77538b9bf/.circleci/config.yml#L80
