### ISSUE TITLE
VolcanoPlot app uses one sliders for lower bound and another slider for upper bound of same variable (effect size).

### ISSUE THREAD

**Issue by mkcor** [plotly/dash-bio#303]
Alternatively, we could use `RangeSlider` (that's exactly what it's for).

_Originally posted by @shammamah in https://github.com/plotly/dash-bio/pull/231/files_

**Comment by mkcor** [comment]
For future reference, it's a `dcc` component: https://dash.plot.ly/dash-core-components/rangeslider

**Comment by shammamah** [comment]
Closed by #315.
