### ISSUE TITLE
Molecule3D dependency doesn't work with React version 16.0 and above

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-bio#313]
In React v15.5, `propTypes` have been moved to an external package (announcement: https://reactjs.org/blog/2017/04/07/react-v15.5.0.html)

From the announcement: 
>Prop types are a feature for runtime validation of props during development. We’ve extracted the built-in prop types to a separate package to reflect the fact that not everybody uses them.
>In 15.5, instead of accessing PropTypes from the main React object, install the prop-types package and import them from there:

The `dash-core-components` library now uses React v16.0 (upgraded from React v15.4), and this results in a breaking change for one of our dependencies (Molecule3D): 

https://github.com/Autodesk/molecule-3d-for-react/blob/ea30999599755f916a1db1d321b198e21348d1a6/src/components/molecule_3d.jsx#L53

https://reactjs.org/warnings/dont-call-proptypes.html#dont-call-proptypes-directly
From the above link: 
>If you don’t fix the warning, this code will crash in production with React 16.

**Comment by shammamah** [comment]
Mol3d issue here: https://github.com/Autodesk/molecule-3d-for-react/issues/36

**Comment by mkcor** [comment]
Well, we've been running React v15.6.2 since #268 ...

**Comment by mkcor** [comment]
We probably want to upgrade to Dash 0.41 and React 16 at the same time. And #304 will be helpful then.

**Comment by shammamah** [comment]
Yeah, but it's only been totally deprecated since v16.0. Everything else works with React 16 -- it's just this one package causing an issue!

**Comment by mkcor** [comment]
Good you narrowed it down! Will make upgrading easier.

So, are you saying that PropTypes still work with React v15.6 but are deprecated?

**Comment by shammamah** [comment]
Yeah, exactly. (see: https://reactjs.org/warnings/dont-call-proptypes.html#dont-call-proptypes-directly)

**Comment by mkcor** [comment]
Ok, so can you please correct the title of this issue? Currently, it says "doesn't *work* with React version 15.5" and you just confirmed that it works but is deprecated. Thanks!

**Comment by shammamah** [comment]
@mkcor Good catch! Just fixed it :)
