### ISSUE TITLE
Improvement of xyz reader

### ISSUE THREAD

**Issue by gVallverdu** [plotly/dash-bio#342]
Hi

I would like to suggest a very small improvement of the xyz reader. The regex is already flexible but it does not consider possible whitespaces at the beginning of the line.

**Describe the "bug"**
If you try to read an xyz file where there is a white space at the beginning of the line the returned `atoms` list of the `dasg_bio.utils.xyz_reader.read_xyz()` function is empty.

For example, you can try using an xyz file from : http://www.nanotube.msu.edu/fullerene/fullerene.php?C=34

**Correction**
The correction (if it may be call like this) is simply to add a possible whitespace at the beginning of the regex. Line 50-52 of `xyz_reader.py`. The current regex is:
```python
r = re.search(
    r'^([\w]+)\s+([\w\.\+\-]+)\s+([\w\.\+\-]+)\s+([\w\.\+\-]+)', 
    line)
```
The following regex accept white spaces at the beginning of the line:

```py
r'^\s*([\w]+)\s+([\w\.\+\-]+)\s+([\w\.\+\-]+)\s+([\w\.\+\-]+)'
```

The other solution is to remove the `^` character but it might me less safe.

Thank you for this nice dash module

**Comment by shammamah** [comment]
@gVallverdu Thanks for bringing this up! I've made a fix in #343 (version 0.0.11rc1 on PyPI is released). Please try out the demo app in that pull request once it's running with the files you mentioned and let me know if it works!
