### ISSUE TITLE
Dash Speck resets to default view state with Dash Loading States

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-bio#354]
**Describe the bug**
Updating the view parameters from the presets results in no corresponding change in the component.

**To Reproduce**
- Change to the "View" tab
- Select "Use presets"
- Change atom style or rendering style

**Expected behavior**
Atom style or rendering style should change. 

**Python version: 3.7.2**

**Python environment (all installed packages in your current environment):**
```
appnope==0.1.0
astroid==2.2.0
atomicwrites==1.3.0
attrs==18.2.0
backcall==0.1.0
biopython==1.73
bleach==3.1.0
certifi==2018.11.29
chardet==3.0.4
chromedriver-binary==2.45.0
Click==7.0
colour==0.1.5
cycler==0.10.0
Cython==0.29.6
dash==0.40.0
dash-bio==0.0.11
dash-bio-utils==0.0.0rc1
dash-core-components==0.45.0
dash-daq==0.1.4
dash-html-components==0.15.0
dash-renderer==0.21.0
dash-table==3.6.0
decorator==4.3.2
docutils==0.14
flake8==3.6.0
Flask==1.0.2
Flask-Compress==1.4.0
GEOparse==1.1.0
gunicorn==19.9.0
idna==2.8
ipdb==0.11
ipython==7.3.0
ipython-genutils==0.2.0
isort==4.3.9
itsdangerous==1.1.0
jedi==0.13.3
Jinja2==2.10
jsonschema==2.6.0
jupyter-core==4.4.0
kiwisolver==1.0.1
lark-parser==0.6.6
lazy-object-proxy==1.3.1
MarkupSafe==1.1.1
matplotlib==3.0.2
mccabe==0.6.1
more-itertools==6.0.0
nbformat==4.4.0
numpy==1.15.4
pandas==0.24.2
ParmEd==3.1.0
parso==0.3.4
percy==2.0.1
pexpect==4.6.0
pickleshare==0.7.5
pkginfo==1.5.0.1
plotly==3.5.0
pluggy==0.9.0
prompt-toolkit==2.0.9
ptyprocess==0.6.0
py==1.8.0
pycodestyle==2.4.0
pyflakes==2.0.0
Pygments==2.3.1
pylint==2.3.0
pypandoc==1.4
pyparsing==2.3.1
pyrsistent==0.14.11
pytest==4.3.0
pytest-dash==2.0.0
python-dateutil==2.8.0
pytz==2018.9
readme-renderer==24.0
requests==2.21.0
requests-toolbelt==0.9.1
retrying==1.3.3
ruamel.yaml==0.15.89
scikit-learn==0.20.2
scipy==1.2.1
selenium==3.141.0
six==1.12.0
sklearn==0.0
tqdm==4.31.1
traitlets==4.3.2
twine==1.13.0
typed-ast==1.3.1
urllib3==1.24.1
waitress==1.2.1
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.14.1
wgetter==0.7
wrapt==1.11.1
```

**Additional context**
N/A

**Comment by shammamah** [comment]
@mj3cheun I assigned you because this issue could be an issue with the React component or the Speck JS itself -- none of the other React components totally reset like this after being wrapped in a loading state.

**Comment by mj3cheun** [comment]
This is an issue with the React component which has been fixed in the refactored version.

**Comment by shammamah** [comment]
Can you post a link to the relevant PR?

**Comment by mj3cheun** [comment]
I haven't made the PR yet since there is still 1 optimization that can still be made but I suppose it is working at 100% as it is and the optimization can come in later or in a seperate PR if it isn't finished on time.

https://github.com/plotly/dash-bio/pull/355

**Comment by shammamah** [comment]
Update, from a conversation we had (putting it here for logging purposes): 

Wrapping a component in a `dcc.Loading` component results in the initial component to be loaded based on the properties that are set in callbacks -- *not* those that are specified when initializing the component within the app layout.

**Comment by shammamah** [comment]
Closing this issue as the problem does not lie with the component itself.
