### ISSUE TITLE
Running `npm audit fix` results in Onco Print show/hide legend test failure

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-bio#391]
As noted in e4df58dd2604a230562407a67f1991e6e6d52bda, the test fails when running automatically. 

It looks like it is something to do with the button, since if it's clicked manually while the test is running, the desired effect occurs (the legend is hidden).

**Comment by mkcor** [comment]
I believe this is the same issue as reported in #214 (duplicate?).

**Comment by shammamah** [comment]
It's not the same issue -- #214 has to do with the default values for the component, and this has to do with the actual tests being broken (and even so, only being broken after running `npm audit fix`).

**Comment by mkcor** [comment]
@shammamah you're right, wishful thinking on my part ;)
