### ISSUE TITLE
About improvement of the Molecule3D component.

### ISSUE THREAD

**Issue by gVallverdu** [plotly/dash-bio#395]
Hello,
I open this issue after a mail exchange with @shammamah. First, thank you to distribute dash-bio !

I finally wrote my a first dash app using dash-bio. The main goal of this application is to map an atomic quantities on the structure using a colorscale. The result is there, select a data in the dropdown on the left, a structure is loaded by default:
https://pychemapps.univ-pau.fr/mosaica/

The aims of these issue is to make a feedback and to list some lacking features. Let me know If you want to split this in several issues.

On the sever, the application is currently working with the following versions of dash and dash-bio. The installation of `dash-bio` downgrades dash to version 0.40. But I got a lot of issues with this dash version, in particular with the dash-table callbacks. Upgrading dash, in my particular applications where I only use `Molecule3DViewer` seems not to raise version issues.

```
dash==1.0.2
dash-bio==0.1.2
dash-core-components==1.0.0
dash-html-components==1.0.0
dash-renderer==1.0.0
dash-table==4.0.2
```

**Features**

Here are the features I would like to be available:

* A ball and stick representation of the molecule as done in the speck component. The Speck component is nice, but it is a little heavy and I cannot change the color of atoms according to the data.
* I am not sure that the `atomLabelsShown` works (or I do not how to do). But it could be great to have the possibility when the mouse go over an atom or when you select that atom to get data or at list to show its name and/or id directly inside the viewer.

The last point in that the atom mapping plus the colorbar could be a component or something from `dash_bio_utils` ? In tools such as VMD for example you can map various quantities (electrostatic potential ...) to a surface using a colorscale.

**Developments**

On a development point of view, I got the following errors/difficulties

* If I try to return the `model_data` attribute of a `Molecule3D` component I got the `unable to load dependencies`
* Again I got the same error If I try to return the `selectedAtomIds` list. 
* I would like to select atoms from the selection of the rows of the table but I do not succeed. In particular, I did not succeed with `SelectedAtomIds` in a callback as output.
 
Let me know if I can help about this and how.

Thank you again

**Comment by shammamah** [comment]
@gVallverdu Thank you for reporting this! I'm glad to hear you like the library. 

Would you be able to provide the code for a minimal Dash app for which those issues pop up?

**Comment by nickmelnikov82** [comment]
Hi,

Features:

1) You can go to the "View" tab and choose the style you would like to see. There are: "Cartoon",
"Sticks" and "Spheres" styles.

2) You can click on the molecule you want and get data
about this molecule in the "View" tab. Also, if you choose
more than 1 molecule in the "View" tab will be displayed a list
of data about the molecules you chose.

Developments:

1) Return model data. You could go to the documentation page -
https://dash.plotly.com/dash-bio/molecule3dviewer and get
the code of default Molecule3d Viewer and there in the
show_selected_atoms function add new div where you will
show the model_data. It will be like this:

`html.Div('Model data: {}'.format(model_data)),`

2) If you add to the show_selected_atom function
this line of the code:

`html.Div('ID: {}'.format(model_data['atoms'][atm]['residue_index'])),`

you also will see the id of the selected atom.

3) In callback selectedAtomIds should be in Input.
You can see the list of a selected atoms and their ids if you
did steps above.
