### ISSUE TITLE
Change dash requirements

### ISSUE THREAD

**Issue by mdelmans** [plotly/dash-bio#399]
Please change dash requirements in requirements.txt

dash==0.40.0 to dash >=0.40.0

**Comment by mdelmans** [comment]
Pull request #400

**Comment by shammamah** [comment]
@mdelmans I've released `0.1.4-rc1`, which has the requirements changed to `dash>=1.0.0`. I'll be addressing this in the Dash docs as well.

**Comment by shammamah** [comment]
@mdelmans I've released `0.1.4`, which is compatible with Dash 1.0.0. Closed in https://github.com/plotly/dash-bio/pull/412.
