### ISSUE TITLE
Clustergram doc intro example raises an error

### ISSUE THREAD

**Issue by joelostblom** [plotly/dash-bio#446]
Running the the following example from https://dash.plot.ly/dash-bio raises an error.

```python
import dash_bio as dashbio
import pandas as pd
import dash_core_components as dcc

df = pd.read_csv(
    'https://raw.githubusercontent.com/plotly/dash-bio' +
    '/master/tests/dashbio_demos/sample_data/clustergram_mtcars.tsv',
    sep='	', skiprows=4
).set_index('model')

data = df.values

component = dcc.Graph(figure=dashbio.Clustergram(
  row_labels=list(df.index),
  width=600,
  color_threshold={'row': 150,
  'col': 700},
  hidden_labels=['row'],
  height=800,
  data=data,
  column_labels=list(df.columns.values)
)[0])
```

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-d099aa02bd49> in <module>
     11 data = df.values
     12 
---> 13 component = dcc.Graph(figure=dashbio.Clustergram(
     14   column_labels=list(df.columns.values),
     15   row_labels=list(df.index),

~/miniconda3/envs/dash-bio/lib/python3.8/site-packages/plotly/basedatatypes.py in __getitem__(self, prop)
    354         # Convert into a property tuple
    355         orig_prop = prop
--> 356         prop = BaseFigure._str_to_dict_path(prop)
    357 
    358         # Handle scalar case

~/miniconda3/envs/dash-bio/lib/python3.8/site-packages/plotly/basedatatypes.py in _str_to_dict_path(key_path_str)
   1333             # Split string on periods.
   1334             # e.g. 'foo.bar_baz[1]' -> ['foo', 'bar_baz[1]']
-> 1335             key_path = key_path_str.split(".")
   1336 
   1337             # Split out bracket indexes.

AttributeError: 'int' object has no attribute 'split'
```

This seems related to the indexing of the clustergram figure, because removing `[0]` makes the code run without raising an error. However, there is still no figure shown, for that the graph part of the code needs to be removed as well. The following works

```python
dashbio.Clustergram(
  column_labels=list(df.columns.values),
  row_labels=list(df.index),
  height=800,
  color_threshold={'row': 150,
  'col': 700},
  width=600,
  data=data,
  hidden_labels=['row'])
```

To me, the dash bio documentation presents these code snippets as independent giving the impression that they can be run as is, but maybe this my misunderstanding and they should always be run in a dashboard as in the detailed documentation when clicking the function's name?

This is in jupyterlab with the following package versions

```
-----
dash      	1.6.1
dash_bio  	0.4.4
dash_core_components	1.5.1
dash_html_components	1.0.2
numpy     	1.17.3
pandas    	0.25.3
plotly    	4.3.0
-----
IPython   	7.9.0
jupyter_client	5.3.3
jupyter_core	4.6.1
notebook  	6.0.1
-----
Python 3.8.0 | packaged by conda-forge | (default, Nov 22 2019, 19:11:38) [GCC 7.3.0]
```

**Comment by shammamah** [comment]
Hey @joelostblom! Thanks for submitting this issue. Good catch -- looks like this change was introduced [a while ago](https://github.com/plotly/dash-bio/blob/master/CHANGELOG.md#changed-5) and never updated in the docs. I'll open up a PR that fixes the code.

**Comment by alexcjohnson** [comment]
> However, there is still no figure shown, for that the graph part of the code needs to be removed as well.

By that I guess you mean the `dcc.Graph(figure=...)` wrapper - right, the assumption in these docs is that they'll be run as part of a Dash app; if you're just in a notebook it won't do you much good to try to directly display a `dcc.Graph`, but a `plotly.py` figure by itself will display fine.

**Comment by joelostblom** [comment]
@shammamah Thanks for fixing this!

@alexcjohnson Yes that's what I was referring to. Could the assumption that all examples are to be run in dash be made explicit in the beginning of the documentation? Since it is also possible to run dash in a notebook, maybe instructions could be included for how to do so? Something like: "These examples are intended to be run as part of a Dash app. If you are using dash-bio in a Jupyter notebook, remove the `dcc.Graph(figure=...)` part of the code"
