### ISSUE TITLE
Add colored labels for preexisting groups in Clustergram

### ISSUE THREAD

**Issue by joelostblom** [plotly/dash-bio#447]
Maybe I am just missing it, but there does not seem to be a way to add colored labels to the rows or columns of the clustergrams. This is a helpful feature as it provides an easy way to spot if prelabelled groups cluster together in the dendrogram. The only colored labels I could find seem to relate to the clusters that can already be seen in the dendrograms rather than any preexisting labels in the data.

To illustrate this point, see the clustermap below pasted from the [seaborn documentation](https://seaborn.pydata.org/generated/seaborn.clustermap.html). Here, the label of each flower species is marked in a different color in the leftmost column and it is easy to see that two of the species mix and has not been perfectly separated by the hierarchical clustering (blue and green).

![image](https://user-images.githubusercontent.com/4560057/69484073-2da10300-0e2f-11ea-803c-b52f882847b6.png)

```
-----
dash      	1.6.1
dash_bio  	0.4.4
dash_core_components	1.5.1
dash_html_components	1.0.2
numpy     	1.17.3
pandas    	0.25.3
plotly    	4.3.0
-----
IPython   	7.9.0
jupyter_client	5.3.3
jupyter_core	4.6.1
notebook  	6.0.1
-----
Python 3.8.0 | packaged by conda-forge | (default, Nov 22 2019, 19:11:38) [GCC 7.3.0]
```

**Comment by bzip2** [comment]
I second the suggestion, for both Plotly heatmaps and Dash bio. Ideally, the user should have the ability to include one or more columns and/or rows of categories based on some property... and to include a legend for each. Dash bio is partly there with row and column group markers.

**Comment by csoulette** [comment]
Q1 looks great for you all so far, how far did you all manage to get this? Although the ability to label the dendogram is great for some users, I think there are a lot who would also benefit from adding a list of color labels for either rows or columns.

**Comment by mbernste** [comment]
This would be an extremely helpful feature. Hoping to see this implemented
