### ISSUE TITLE
Make plots work with pandas dataframes as input

### ISSUE THREAD

**Issue by joelostblom** [plotly/dash-bio#451]
From the documentation, it seems like some dashbio plots (e.g. volcano and manhattan) already work with pandas dataframes, while others (e.g. clustergram) does not. I haven't looked through all the plots, so I don't know how generalizable this suggestion is, but at least for clustergram plots it would be helpful to pass data frames and string references to dataframe columns as inputs.

As an example, instead of writing

```python
db.Clustergram(iris.select_dtypes('number').to_numpy(), row_labels=iris['species'].to_list())
```

it would be more intuitive to write

```python
db.Clustergram(iris, row_labels='species')  # or a reference to a column with color names
```

**Comment by mkcor** [comment]
Hi @joelostblom,

Once #478 is reviewed, approved, and merged, you will be able to run `db.Clustergram(iris)`!

I will troubleshoot #449 before passing the DataFrame's labels to `column_labels` and/or `row_labels` whenever these arguments aren't specified.
