### ISSUE TITLE
Set up circle-ci for monorepo-deployment

### ISSUE THREAD

**Issue by ycaokris** [plotly/dash-bio#455]
Similar as [dash-sample-apps](https://github.com/plotly/dash-sample-apps),   Change circle-ci deployment schema for batch deploy to gallery. 

This could be pooled with https://github.com/plotly/dash-bio/issues/435 which needs:

1) Remove old GA from circle-ci settings and remove them during deployment https://github.com/plotly/dash-bio/blob/74e51737830ac08da3799189ccb41d65009e0ceb/.circleci/config.yml#L142-L143

2) During deployment workflow, add a `predeploy.py`(https://github.com/plotly/dash-sample-apps/blob/master/predeploy.py) for inserting index string after `if __name__ == 'main': `
under app directory.

@josegonzalez

**Comment by josegonzalez** [comment]
Does this get deployed to playground and gallery as well, or just gallery? In other words, is the setup supposed to be the same as for dash-sample-apps?

**Comment by ycaokris** [comment]
It'll be helpful to use test server before production - I'm up to @shammamah

**Comment by josegonzalez** [comment]
- test == playground
- production == gallery

Is that correct?

**Comment by ycaokris** [comment]
> * test == playground
> * production == gallery
> 
> Is that correct?

Correct!

**Comment by ycaokris** [comment]
looks like gallery deploy still needs to be fixed. @josegonzalez

**Comment by josegonzalez** [comment]
@ycaokris all apps should be deployed now, as of https://circleci.com/gh/plotly/dash-bio/5626

**Comment by ycaokris** [comment]
> @ycaokris all apps should be deployed now, as of https://circleci.com/gh/plotly/dash-bio/5626

Thanks! 👍
