### ISSUE TITLE
Data Table prevents other callbacks until it is rendered first

### ISSUE THREAD

**Issue by christopherjeon** [plotly/dash-bio#477]
**Describe the bug**
I recently fixed a bug on the Circos app that basically blocked a certain callback because it had a data table prop as an input. Here is a detailed issue from the Dash repo: https://github.com/plotly/dash/issues/1105

This issue was created so we could keep track of possible changes needed again for the Circos app.

**Comment by emmeb** [comment]
Closed as [issue#1105](https://github.com/plotly/dash/issues/1105) is fixed
