### ISSUE TITLE
Dash_Bio Manhattan plot attempting to assign an invalid property when creating graph

### ISSUE THREAD

**Issue by harris-2374** [plotly/dash-bio#486]
**Describe the bug**
When I go to run my dash app and have it produce a Manhattan plot from my own input data, it raises a ValueError. The exact error is: (Invalid property specified for object of type plotly.graph_objs.scattergl.Marker: 'name'). This is not a value that the user sets, but rather something the Manhattan plot function sets. 

**To Reproduce**
1. I have a data set that I am loading in that is not set up in the strict CHR, BP, P, SNP, GENE column headers.
2. I then alter the pandas DataFrame to conform to the column names requested by the Manhattan plot function. Because I do not have nor need the data for SNP, ZSCORE, EFFECTSIZE, GENE, or DISTANCE, they are just NA string values.
3. I then conform the columns to the correct data types and call the Manhattan plot function. It is at this time that the error is raised. 

**Expected behavior**
I would expect to have a Manhattan plot created and displayed.

**Screenshots**
If applicable, add screenshots to help explain the issue.

**Python version: [e.g., 3.7.2]**
- Python Version 3.6.4

**Python environment (all installed packages in your current environment):**
 - Package                   Version
astroid                   2.3.3  
biopython                 1.76   
Click                     7.0    
colorama                  0.4.3  
dash                      1.9.0  
dash-bio                  0.4.6  
dash-bootstrap-components 0.8.3  
dash-core-components      1.8.0  
dash-daq                  0.3.3  
dash-html-components      1.0.2  
dash-renderer             1.2.4  
dash-table                4.6.0  
Flask                     1.1.1  
Flask-Compress            1.4.0  
future                    0.18.2 
isort                     4.3.21 
itsdangerous              1.1.0  
Jinja2                    2.11.1 
joblib                    0.14.1 
lazy-object-proxy         1.4.3  
MarkupSafe                1.1.1
mccabe                    0.6.1
numpy                     1.18.1
pandas                    1.0.1
pip                       20.0.2
plotly                    4.5.1
pyfaidx                   0.5.8
pylint                    2.4.4
python-dateutil           2.8.1
pytz                      2019.3
retrying                  1.3.3
scikit-learn              0.22.1
scipy                     1.4.1
setuptools                28.8.0
six                       1.14.0
typed-ast                 1.4.1
Werkzeug                  1.0.0
wrapt                     1.11.2

**Additional context**

**Comment by nickmelnikov82** [comment]
I checked the #486 issue about uploading another data.
I downloaded another data for the Manhatten plot and it build
a graph for this data.

Steps:
1. Download another data.csv file for the Manhatten plot.
2. Change columns names as need by the function ManhattenPlot.
3. Have created and displayed Manhatten plot.

The columns that are needed for the ManhattanPlot function:
1) CHR
2) BP
3) P
4) SNP
5) ZSCORE
6) EFFECTSIZE
7) GENE
[data.csv](https://github.com/plotly/dash-bio/files/7138223/data.csv)

8) DISTANCE
They are the same as in the default data.csv file.
My data.csv file is attached.
