### ISSUE TITLE
Add Ideogram annotations from a local file

### ISSUE THREAD

**Issue by yonatans2** [plotly/dash-bio#495]
Hi,

TBH I'm not sure if this post fits as an issue or something that should be on the Dash community forum.

Anyway, I want to be able to load a locally-saved annotations JSON into an Ideogram figure. If I understood the [documentation](https://dash.plot.ly/dash-bio/ideogram) correctly, currently the only ways to load annotations is to supply a URL via the [annotationsPath] property, or an explicit list of dicts via [annotations].

Also, is there an official format for the annotations? I tried to infer it from the example annotations found in the [code](https://github.com/plotly/dash-bio/blob/master/tests/dashbio_demos/dash-ideogram/app.py) of the demo, and also tried to construct a list of dicts as the documentation suggests, but nothing works.

Thanks,
Yonatan

**Comment by pajucon** [comment]
You are correct in that remote URLs are only allowed currently. 
I hosted my JSON on github pages to mimic the example and it worked.

I think annotations_path and annotations are mutually exclusive. If you are providing an annotations path you should adhere to the required JSON format (and not supply input to the annotations component).

Here is a piece of my JSON mimicking the 'tracks' example. 

{"keys":  ["name", "start", "length", "trackIndex"], 
 "annots": [{ "chr": "1", 
                   "annots": [["rs25", 5974955, 0, 1], ["rs49", 11949909, 0, 2], ["rs73", 17924863, 0, 1]]
                 }]
}

The type of 'annotations_layout' dictates the JSON format. You have to dig around the examples/source to find the correct JSON format for your desired display type. 

https://github.com/eweitz/ideogram/blob/master/docs/annotations.md

**Comment by nickmelnikov82** [comment]
Hi Yonatan,

To load the JSON file that is on the server you should take code from documentation - https://dash.plotly.com/dash-bio/ideogram :

```
import dash_design_kit as ddk
import dash_bio as dashbio

dashbio.Ideogram(
    id='ideogram-annotations',
    chromosomes=['X', 'Y'],
    annotationsPath='https://eweitz.github.io/ideogram/data/annotations/SRR562646.json'
) 
```

I did it and it works as expected.

Best wishes,
Nick.
