### ISSUE TITLE
Set z / heat values to original values (not distance) in matrix for Clustergram

### ISSUE THREAD

**Issue by ijmiller2** [plotly/dash-bio#505]
Dear dash-bio team,

I'm wondering if there's a way to set the heat values and/or 'z' values in the clustergram output to the original values of the input matrix instead of the calculated distance metric? Or at least I think this is what's being displayed.

It's certainly useful to calculate distance to create the dendrograms, but it would be more useful for me to see the values that are originally provided in the matrix (in this case protein levels) instead of euclidean distance when hovering over the heatmap. Even if it meant just adding more options/info to the hover tool, that could work.

Maybe this is already and option and I'm just missing something in the [documentation](https://dash.plotly.com/dash-bio/clustergram). Happy to try to clarify or provide more detailed examples if it helps.

Thanks in advance for the feedback,
Ian

**Comment by Payamch** [comment]
@ijmiller2 unfortunately, the documentation is only showing some examples and it's not actual documentation that explains every input. For that, you need to look into the source code.

I had the same issue as yours, so looking into in-code documentation, you realize that this can be done only with setting center_values=False.

Ex:
```import pandas as pd

import dash_core_components as dcc
import dash_bio as dashbio


df = pd.read_csv('https://raw.githubusercontent.com/plotly/dash-bio-docs-files/master/clustergram_mtcars.tsv',
                 sep='	', skiprows=4).set_index('model')

columns = list(df.columns.values)
rows = list(df.index)

clustergram = dashbio.Clustergram(
    data=df.loc[rows].values,
    row_labels=rows,
    column_labels=columns,
    center_values=False, #this one
    color_threshold={
        'row': 250,
        'col': 700
    },
    height=800,
    width=700,
    color_map= [
        [0.0, '#636EFA'],
        [0.25, '#AB63FA'],
        [0.5, '#FFFFFF'],
        [0.75, '#E763FA'],
        [1.0, '#EF553B']
    ]
)

dcc.Graph(figure=clustergram)  ```

**Comment by ijmiller2** [comment]
Thank you, @Payamch! I tried that and it seems to work as expected. I also noticed that you can update the z values in the underlying heatmap matrix after the fact with:

`clustergram['data'][-1]['z'] = df.values`

But this is far clunkier and doesn't handle the fact the matrix has been resorted based on the dendrogram order. So I didn't go much further than that.

And thanks for the insight about the in code documentation. That will be helpful going forward. 

Did you mean with `dir(clustergram)` and `help(clustergram)`? Or are you talking about looking at the actual underlying source code to find that info?

Thanks again,
Ian

**Comment by nickmelnikov82** [comment]
Hi Ian,

thanks for being interested in this question. The default clustegram which is on the documentation page - https://dash.plotly.com/dash-bio/clustergram
is built based on this csv file https://raw.githubusercontent.com/plotly/dash-bio-docs-files/master/clustergram_mtcars.tsv.

Firstly, I set the `center_values ` variable to `False`. After this, when I hover to the clustegram I get the original matrix values.

Secondly, this data is the same as the data in the csv file.

So, here is my code:

```
import pandas as pd

import dash
from dash.dependencies import Input, Output
import dash_bio as dashbio
import dash_html_components as html
import dash_core_components as dcc

app = dash.Dash(__name__)

df = pd.read_csv(
    'https://raw.githubusercontent.com/plotly/dash-bio-docs-files/master/' +
    'clustergram_mtcars.tsv',
    sep='	', skiprows=4
).set_index('model')

columns = list(df.columns.values)
rows = list(df.index)

app.layout = html.Div([
    "Rows to display",
    dcc.Dropdown(
        id='clustergram-input',
        options=[
            {'label': row, 'value': row} for row in list(df.index)
        ],
        value=rows[:10],
        multi=True
    ),

    html.Div(id='my-clustergram')
])


@app.callback(
    Output('my-clustergram', 'children'),
    Input('clustergram-input', 'value')
)
def update_clustergram(rows):
    if len(rows) < 2:
        return "Please select at least two rows to display."

    return dcc.Graph(figure=dashbio.Clustergram(
        data=df.loc[rows].values,
        column_labels=columns,
        row_labels=rows,
        color_threshold={
            'row': 250,
            'col': 700
        },
        hidden_labels='row',
        height=800,
        width=700,
        center_values=False
    ))


if __name__ == '__main__':
    app.run_server(debug=True)
```

Also, you can find the source code here - https://github.com/plotly/dash-bio.

Best wishes,
Nick.
