### ISSUE TITLE
how to save the figure

### ISSUE THREAD

**Issue by yanglq-bio** [plotly/dash-bio#509]
Hello,I recently learned about the dash-bio Library and found it interesting, so I tried to run the code, taking clustergram as an example, and asked for an answer.
1. how to save the picture
When I run a python script,I hope it can save the picture Automatically,but now,I need to open the html and save it.I looked at the parameters carefully, and there seems to be no mention of saving pictures.

2.Whether the legend of clustergram can be moved ?
I found the legend and heat map part too close together, resulting in the heat map label was blocked

**Comment by alexcjohnson** [comment]
Clustergram, like several other (but not all) of the dash_bio components, is just a wrapper around plotly.py, the Python interface to the plotly.js graphing library. Its output is a `go.Figure` object, so you can use https://plotly.com/python/creating-and-updating-figures/ to move the legend (eg `fig.update_layout(legend_x=...)`) and to save the picture https://plotly.com/python/static-image-export/

In general it's better to ask usage questions at https://community.plotly.com/ so we can keep github focused on bug reports and feature requests. Thanks!
