### ISSUE TITLE
Repeated zooming after updating a Molecule3dViewer

### ISSUE THREAD

**Issue by rmcgibbo** [plotly/dash-bio#510]
**Describe the bug**
I have a small dash app that includes a 2D graph and a Molecule3dViewer, such that when I click on points in the 2D graph I update the Molecule3dViewer. My dash callback returns something like this, following the example here.

```
    return dash_bio.Molecule3dViewer(
            id='mol-3d',
            selectionType='atom',
            modelData=mdata,
            styles=data_style,
            selectedAtomIds=[],
            backgroundOpacity='0',
            atomLabelsShown=False,
        )
```
I noticed that when I repeatedly click on the graph, each time the Molecule3dViewer updates, the molecule shrinks slightly.

**Expected behavior**
My expectation would be that updating the Molecule3dViewer multiple times would not repeatedly shrink the displayed molecule.

I believe that the issue is that this line of code executes every time the Molecule3dViewer is updated, causing the effective zoom to get decreased multiplicatively. I presume the intent was for this to only happen once. https://github.com/plotly/dash-bio/blob/master/src/lib/fragments/Molecule3dViewer.js#L18

I installed a modified version of the code on my machine where I simply replaced that number with 1.0 by manually editing the compressed javascript bundle, and it worked, which I think confirms my diagnosis.

**Comment by alexcjohnson** [comment]
Thanks for the report @rmcgibbo - I don't see any discussion of this 0.8 factor anywhere in this repo, perhaps the thinking was that the default zoom is too tight and we want a bit of a buffer? If that's it, I wonder if we could just replace `glviewer.center();` on the previous line with `glviewer.zoomTo()` which, if I'm reading the [docs](http://3dmol.csb.pitt.edu/doc/$3Dmol.GLViewer.html#zoomTo) correctly seems like it will set both the center and the scale, unlike [`center`](http://3dmol.csb.pitt.edu/doc/$3Dmol.GLViewer.html#center). That would reset to the new data, then we could still apply the 0.8 zoom afterward.

**Comment by dgasmith** [comment]
I can confirm that this is still an issue and that `zoomTo` on new data would fix it.

\wave @rmcgibbo !

**Comment by HammadTheOne** [comment]
Thanks for pointing it out! I'll have a PR open for this shortly and we'll have this fixed in the next release of `dash-bio`. While we're on the topic, would it be helpful in your apps to have a prop exposed for `zoomTo` so that it can interact with other Dash components?
