### ISSUE TITLE
Abnormal memory consumption of Molecule3dViewer

### ISSUE THREAD

**Issue by m97** [plotly/dash-bio#511]
Molecule3dViewer application memory usage increases while rotating molecule. By increase I mean in order of GB, which consumes whole system memory to the point of crash.

To Reproduce:
Operating system - Linux Mint 20
Web Browser - Google Chrome Version 84.0.4147.105 (Official Build) (64-bit)

1. Open demo (for example https://dash.plotly.com/dash-bio/molecule3dviewer). 
2. Start rotating molecule while monitoring ram consumption. 

Expected behavior:
Interacting with displayed molecule should not lead to dramatic increase of ram consumption and system crash. 

Screenshots:
Before rotating displayed molecule:
![before_rotation](https://user-images.githubusercontent.com/3457821/89644193-a9f14e80-d8b7-11ea-98d9-f669fe793e5d.png)

After few seconds of rapid rotation:
![after_rotation](https://user-images.githubusercontent.com/3457821/89644192-a958b800-d8b7-11ea-932e-9d342cfca36d.png)

Python version: Python 3.8.2

Python enviroment:

> apt-clone                 0.2.1               
apturl                    0.5.2               
attrs                     19.3.0              
backcall                  0.1.0               
beautifulsoup4            4.8.2               
biopython                 1.77                
bleach                    3.1.1               
blinker                   1.4                 
Brlapi                    0.7.0               
Brotli                    1.0.7               
certifi                   2019.11.28          
chardet                   3.0.4               
Click                     7.0                 
colorama                  0.4.3               
colour                    0.1.5               
command-not-found         0.3                 
configobj                 5.0.6               
crudini                   0.9.3               
cryptography              2.8                 
cupshelpers               1.0                 
cycler                    0.10.0              
dash                      1.14.0              
dash-bio                  0.4.8               
dash-bio-utils            0.0.5               
dash-bootstrap-components 0.10.3              
dash-core-components      1.10.2              
dash-html-components      1.0.3               
dash-renderer             1.6.0               
dash-table                4.9.0               
dbus-python               1.2.16              
decorator                 4.4.2               
defer                     1.0.6               
defusedxml                0.6.0               
distro                    1.4.0               
entrypoints               0.3                 
Flask                     1.1.2               
Flask-Compress            1.5.0               
forcelayout               1.0.6               
future                    0.18.2              
GEOparse                  2.0.1               
grpcio                    1.16.1              
html5lib                  1.0.1               
httplib2                  0.14.0              
idna                      2.8                 
ifaddr                    0.1.6               
importlib-metadata        1.5.0               
iniparse                  0.4                 
ipykernel                 5.2.0               
ipython                   7.13.0              
ipython-genutils          0.2.0               
itsdangerous              1.1.0               
jedi                      0.15.2              
Jinja2                    2.10.1              
joblib                    0.16.0              
jsonschema                3.2.0               
jupyter-client            6.1.2               
jupyter-console           6.0.0               
jupyter-core              4.6.3               
keyring                   18.0.1              
kiwisolver                1.2.0               
launchpadlib              1.10.13             
lazr.restfulclient        0.14.2              
lazr.uri                  1.0.3               
louis                     3.12.0              
macaroonbakery            1.3.1               
Mako                      1.1.0               
Markdown                  3.1.1               
MarkupSafe                1.1.0               
matplotlib                3.3.0               
meson                     0.53.2              
mistune                   0.8.4               
more-itertools            4.2.0               
nbconvert                 5.6.1               
nbformat                  5.0.4               
nemo-emblems              4.6.0               
netifaces                 0.10.4              
networkx                  2.4                 
nose                      1.3.7               
notebook                  6.0.3               
numpy                     1.17.4              
oauthlib                  3.1.0               
onboard                   1.4.1               
packaging                 20.3                
PAM                       0.4.2               
pandas                    1.1.0               
pandocfilters             1.4.2               
ParmEd                    3.2.0               
parso                     0.5.2               
periodictable             1.5.2               
pexpect                   4.6.0               
pickleshare               0.7.5               
Pillow                    7.0.0               
pip                       20.0.2              
plotly                    4.9.0               
prometheus-client         0.7.1               
prompt-toolkit            2.0.10              
protobuf                  3.6.1               
psutil                    5.5.1               
PyAudio                   0.2.11              
pycairo                   1.16.2              
pycrypto                  2.6.1               
pycups                    1.9.73              
pycurl                    7.43.0.2            
Pygments                  2.3.1               
PyGObject                 3.36.0              
PyICU                     2.4.2               
pyinotify                 0.9.6               
PyJWT                     1.7.1               
pymacaroons               0.13.0              
pymol                     2.3.0               
PyNaCl                    1.3.0               
PyOpenGL                  3.1.0               
pyparsing                 2.4.6               
pyparted                  3.11.2              
PyQt5                     5.14.1              
PyQtWebEngine             5.14.0              
pyRFC3339                 1.1                 
pyrsistent                0.15.5              
python-apt                2.0.0+ubuntu0.20.4.1
python-dateutil           2.7.3               
python-debian             0.1.36ubuntu1       
python-xapp               2.0.1               
python-xlib               0.23                
pytz                      2019.3              
pyxattr                   0.6.1               
pyxdg                     0.26                
PyYAML                    5.3.1               
pyzmq                     18.1.1              
reportlab                 3.5.34              
requests                  2.22.0              
requests-unixsocket       0.2.0               
retrying                  1.3.3               
scikit-learn              0.23.2              
scipy                     1.5.2               
SecretStorage             2.3.1               
Send2Trash                1.5.0               
sessioninstaller          0.0.0               
setproctitle              1.1.10              
setuptools                45.2.0              
simplejson                3.16.0              
sip                       4.19.21             
six                       1.14.0              
soupsieve                 1.9.5               
system-service            0.3                 
systemd-python            234                 
terminado                 0.8.2               
testpath                  0.4.4               
threadpoolctl             2.1.0               
tinycss2                  1.0.2               
tornado                   5.1.1               
tqdm                      4.48.2              
traitlets                 4.3.3               
ubuntu-advantage-tools    20.3                
ubuntu-drivers-common     0.0.0               
ufw                       0.36                
Unidecode                 1.1.1               
urllib3                   1.25.8              
urwid                     2.0.1               
wadllib                   1.3.3               
wcwidth                   0.1.8               
webencodings              0.5.1               
Werkzeug                  1.0.1               
wheel                     0.34.2              
xkit                      0.0.0               
youtube-dl                2020.3.24           
zeroconf                  0.24.4              
zim                       0.72.0              
zipp                      1.0.0

**Comment by NatureGeorge** [comment]
Also encounter this issue.  This seems to be a common issue with plotly's 3d viewer(harmless for small dataset) but serious in `Molecule3dViewer`.
