### ISSUE TITLE
XYZ Files

### ISSUE THREAD

**Issue by MQSchleich** [plotly/dash-bio#521]
Hey, 

I updated the parser, such that he can read xyz-files. If you want me to contribute it let me know. 
Cool project! 

Best, 
MQ

**Comment by HammadTheOne** [comment]
Hello @MQSchleich,

Thank you for your interest! In the [`dash-bio-utils`](https://github.com/plotly/dash-bio-utils/blob/master/dash_bio_utils/xyz_reader.py) repo we have an XYZ reader helper script which parses an XYZ file and returns a Python dictionary of the contents. Is this similar to what you had in mind?

**Comment by MQSchleich** [comment]
Hey @HammadTheOne 
Yes, this is similar. I just extended the code in the parser, because I was working with xyz-files and the dash-app just accepted .pdb files. I did it with my own script, but could rewrite it with your script. Let me know if you want to use this, I would be happy to share (if it is not redundant). 

Another thing: Is there any Balls-And-Sticks Visualisation already? 

Thanks, 
MQ

**Comment by HammadTheOne** [comment]
It would definitely be nice to have an addition to the parser that might make it compatible with `.pdb` files as well. If you'd like to open a PR to https://github.com/plotly/dash-bio-utils/blob/master/dash_bio_utils/xyz_reader.py with your changes, I would be happy to take a look at them and see if we can add them in. 

As for ball-and-stick visualizations, a few `dash-bio` components currently support them - the [`Speck`](https://github.com/plotly/dash-bio/tree/master/tests/dashbio_demos/dash-speck) component takes XYZ files as an input and has a ball-and-stick atom preset. The [`MoleculeViewer 3d`](https://github.com/plotly/dash-bio/tree/master/tests/dashbio_demos/dash-molecule-3d-viewer) supports ball and stick views independently, and the newly added [NGL Moleculeviewer](https://github.com/plotly/dash-bio/tree/master/tests/dashbio_demos/dash-ngl-moleculeviewer) also supports ball-and-stick views, and takes a PDB or .cif file as input.

**Comment by MQSchleich** [comment]
Hey, 

thanks for your reply. Especially, the knowledge about the molecular viewer is helpful. I refactor the stuff and open a PR on that. 

Thanks,

**Comment by HammadTheOne** [comment]
Closing this issue for now.
