### ISSUE TITLE
Molecule3D shapes and isosurfaces

### ISSUE THREAD

**Issue by JonKragskow** [plotly/dash-bio#526]
I'm enjoying using the 3D viewer in dash-bio, but I have one question.

Seeming as the 3D viewer is taken from the react wrapper of 3dmol.js, I was wondering why the `shapes` and `isosurface` features aren't implemented? It would be **really** nice to have these available to use in Dash.

Cheers!

**Comment by jackparmer** [comment]
Can you please link to a shape and isosurface example in 3dmol.js? (Such as on codeine or in their docs)

**Comment by JonKragskow** [comment]
Sure, their homepage has an example of an isosurface and of shapes on top of a molecule.

http://3dmol.csb.pitt.edu/index.html <http://3dmol.csb.pitt.edu/index.html>

If you view source on that page you can see the js they use to do both, line 19 to line 72

**Comment by HammadTheOne** [comment]
With `dash-bio-0.7.0` the Molecule3d component now includes support for isosurfaces and basic shapes.
