### ISSUE TITLE
Circos tooltip not centered on cursor when scrolling

### ISSUE THREAD

**Issue by surchs** [plotly/dash-bio#531]
The tooltip of the circos component appears to be centered on the viewport and gets shifted if the viewport is scrolled. This can be seen in the [app gallery](https://dash-gallery.plotly.host/dash-circos/) or in a custom app.
![circos_tooltip_offset](https://user-images.githubusercontent.com/1302022/100392300-18dbea00-3004-11eb-92fb-3738a523551b.gif)

**Comment by Samcro5C** [comment]
Has anyone found a solution or a workaround for this?
