### ISSUE TITLE
Resizing needle plot

### ISSUE THREAD

**Issue by priesgo** [plotly/dash-bio#545]
I would like to resize the needle plot so I can make it arbitrarily wide. The default size is a bit smaller than a third of my screen size and considering the legend it is too small to provide a good user experience.

PS: apologies if this is not the right channel to communicate such requirements

**Comment by alexcjohnson** [comment]
This would be a very nice addition - `width` and `height` props are the obvious ones, it could also be useful to include a way to override the plot `config` so you could turn on `responsive` mode and have the plot get its size from its container.

This would be a straightforward addition if you or anyone else is interested in making a PR - a couple new props added to https://github.com/plotly/dash-bio/blob/master/src/lib/components/NeedlePlot.react.js and piped through to the plot in https://github.com/plotly/dash-bio/blob/master/src/lib/fragments/NeedlePlot.react.js

**Comment by priesgo** [comment]
Thanks @nickmelnikov82 !
