### ISSUE TITLE
Labels of domains in needle plot are misplaced

### ISSUE THREAD

**Issue by priesgo** [plotly/dash-bio#546]
**Describe the bug**
When providing domains to the needle plot, some of the labels are not placed in the same coordinates as the domain.

**To Reproduce**
I used these domains from SARS-Cov-2 spike protein:
```
[
{'name': 'CoV_S2', 'coord': '22274-22795'}, 
{'name': 'bCoV_S1_RBD', 'coord': '21912-22089'}, 
{'name': 'bCoV_S1_N', 'coord': '21596-21900'}, 
{'name': 'CoV_S1_C', 'coord': '22099-22155'}
]
```
The label for CoV_S2 is placed somewhere around position 24500.

**Expected behavior**
I would expect at least for the labels to be at the positions where the domains are. Because some times the labels can be very close together it would be very good to be available to tilt the labels in order to have some readability or being able to completely remove the labels from the domains and show them only on hover for instance. 

**Screenshots**
![Screenshot from 2021-02-26 14-04-19](https://user-images.githubusercontent.com/3140648/109303854-a7e2e300-783b-11eb-8f8f-590e951b0517.png)

**Python version: [e.g., 3.7.2]**
Python 3.8.5

**Python environment (all installed packages in your current environment):**
```
attrs==20.3.0
biopython==1.78
bokeh==2.2.3
Brotli==1.0.9
certifi==2020.12.5
chardet==3.0.4
click==7.1.2
cloudpickle==1.6.0
coloredlogs==15.0
coverage==5.4
cyvcf2==0.30.4
dash==1.19.0
dash-bio==0.6.1
dash-core-components==1.15.0
dash-html-components==1.1.2
dash-renderer==1.9.0
dash-table==4.11.2
dask==2.30.0
distributed==2.30.0
Flask==1.1.2
Flask-Compress==1.8.0
fsspec==0.8.5
future==0.18.2
HeapDict==1.0.1
humanfriendly==9.1
idna==2.10
iniconfig==1.1.1
itsdangerous==1.1.0
Jinja2==2.11.2
joblib==1.0.1
locket==0.2.1
logzero==1.6.3
MarkupSafe==1.1.1
msgpack==1.0.2
numpy==1.19.5
packaging==20.8
pandas==1.2.1
partd==1.1.0
Pillow==8.1.0
plotly==4.14.3
pluggy==0.13.1
pprintpp==0.4.0
psutil==5.8.0
psycopg2-binary==2.8.6
py==1.10.0
pybiomart==0.2.0
pycountry==20.7.3
pycountry-convert==0.7.2
pyparsing==2.4.7
pytest==6.2.2
pytest-cov==2.11.1
pytest-mock==3.5.1
python-dateutil==2.8.1
pytz==2020.5
PyYAML==5.4.1
repoze.lru==0.7
requests==2.25.0
requests-cache==0.5.2
retrying==1.3.3
scikit-learn==0.24.1
scipy==1.6.1
six==1.15.0
sortedcontainers==2.3.0
SQLAlchemy==1.3.20
tblib==1.7.0
tenacity==6.3.1
threadpoolctl==2.1.0
toml==0.10.2
toolz==0.11.1
tornado==6.1
typing-extensions==3.7.4.3
urllib3==1.26.2
Werkzeug==1.0.1
zict==2.0.0
```

**Additional context**

**Comment by jackparmer** [comment]
@HammadTheOne maybe we can add props for x-axis text rotation and margin spacing to this component
