### ISSUE TITLE
how to modify circos plot chr name？

### ISSUE THREAD

**Issue by Lix1993** [plotly/dash-bio#561]
I wanna change chr name display in circos plot， but I cannot find any code about how to draw the circos plot, what should I do?

**Comment by nickmelnikov82** [comment]
Hi @Lix1993,

https://dash.plotly.com/dash-bio/circos names on the graph come from the [json input file](https://github.com/plotly/dash-bio/blob/4d3fb48226722857eeb4bb51f9be90592fc95589/tests/dashbio_demos/dash-circos/data/graph_data.json). 

If you change the value of "chr" in the example file from "chr9", to "new_value", it will change in the graph.

Hope this will help you!

Best wishes,
Nick.
