### ISSUE TITLE
missing DatasetLoader()

### ISSUE THREAD

**Issue by librahoo** [plotly/dash-bio#584]
In the Dash-Bio Documentation, most examples require python function DatasetLoader() to load formatted data to process the raw data. It seemed like this function should be import by dash_docs.utils (some examples showed "from dash_docs.utils import DatasetLoader"), however, there is no utils.py under the dash_docs/ folder, is this file missing?

**Comment by smallstepman** [comment]
@emmeb @nickmelnikov82 perhaps we can do some 
![image](https://user-images.githubusercontent.com/21069150/138364614-7898170b-8b8a-44bb-98ab-deea38b917c5.png)

1. the hard way (not sure how): swap definition of `urllib.request.urlopen` for our own (`DatasetLoader`) - this would make the content in docs appear as everyday-python to docs users, but would lazy load the datasets 
2. the easy way: use `str.replace()` to modify our docs is such way, that one version (with `DatasetLoader`) is sent to block with rendered component, while second version (with `urllib.request.urlopen`) is sent to block which displays markdown/code. [Here](https://github.com/plotly/ddk-dash-docs/blob/ce339d15a82606db9e4a3241baef799fe3cc6e01/dash_docs/reusable_components/dash_docs_markdown.py#L268) is where the change could poentially happen
