### ISSUE TITLE
Dash Bio apps - initial impressions

### ISSUE THREAD

**Issue by jackparmer** [plotly/dash-bio#64]
First-level impressions clicking through Dash Bio gallery beta apps: https://dash-gallery.plotly.host/dash-bio

### Header

Would be great to have a GitHub link in the upper-right of the header that links to the code for each app on GitHub.

### Dash Circos

- [x] A lot of stuff in this sidebar. Pretty overwhelming. Maybe try organizing into tabs within the sidebar? Eg perhaps could organize tabs as, Data | Layout | Events | Upload

<img width="540" alt="image" src="https://user-images.githubusercontent.com/1865834/49317996-a3d48900-f4ab-11e8-92ee-26cf524c0686.png">

- [x] Add a dropdown of a few different datasets? 

### Dash Clustergram

- [x] Heatmap is a bit small. Maybe put the right-hand column on the left side instead, and try to make the clustergram go full-bleed to the right edge of the screen? Usually sidebars like this are on the left hand side.
- [x] Would be nice to have a dropdown with a few classic clustergram data sets. Look at what the R clustergram packages and shiny apps use (eg heatmaply). Eg the `mtcars` dataset is a "classic:"

https://cran.rstudio.com/web/packages/heatmaply/vignettes/heatmaply.html

### Dash Ideogram

- [x] Needs margin on the left-hand side. Bugs me that controls are touching window edge.
- [x] Make an issue in the original ideogram JS repo with a link to this app, to share and get feedback. Maybe will motivate the PI to address some of the issues you've raised. 

### Manhattan Plot

- [x] Hover mode should be `closest` by default
- [x] The "Visualize genome wide association studies..." description should  should have a top margin so it's not touch the top header.

### Sequence Viewer 

- [x] Not sure what "Entry to view" is
- [x] Might want a dropdown with a few other sequences besides insulin 
- [ ] Would be great to combine this with 3d molecule viewer if there's a way that makes sense
- [x] vertical space between labels
- [x] Sequence doesn't wrap
<img width="234" alt="image" src="https://user-images.githubusercontent.com/1865834/49323612-f5443e80-f4d2-11e8-983c-0b3c4bf8073b.png">

### Dash needle plot

- [x] Labels such as `Stem thickness` are too large in font-size IMO. 
- [x] I only see one sample dataset in the dropdown - need to add more. A bunch here:
https://github.com/jackparmer/react-needle-plot/tree/master/src/data
On one of the Dash Bio calls I thought you had also found others in a Nature paper.
- [x] Should be a left-side margin so that controls and labels don't touch the edge of the window
<img width="388" alt="image" src="https://user-images.githubusercontent.com/1865834/49320415-5b6e9880-f4b6-11e8-8d36-c08180b3dd93.png">

### Volcano

- [ ] This app doesn't do much. Should maybe reduce the opacity of the points above the threshold? To make it more interesting, could add 2 overlaid histograms to the app - one histogram is all of the data and the other histogram is the data above the threshold. When the threshold is zero, the histograms are the same.
- [ ] Get rid of "Lower effect size" and "Upper effect size" controls. They just reset the x-axis range which I don't think is very interesting.
- [x] Set default `hover mode` to `closest`

### Remaining apps

- [ ] @nchtra @jackluo @wilzbach Need your demo apps up here once your components are finished and merged

**Comment by gzork** [comment]
> Definitely would like to understand why a conda buildpack isn't working
@jackparmer (I kept this unread to answer with more context). There is more info in this issue https://github.com/plotly/streambed/issues/11803, but TL;DR is basically we have to support different versions of Miniconda, which is not done by the official buildpack (which is deprecated by Heroku), and we need to support Isolated/Airgapped installs, which is specific to our product offering unlike Heroku. but this is a WIP, and we should be able to support conda dash app deployments in DDS in `3.1`.
