### ISSUE TITLE
Does dash-bio use a version of IGV with Apache Log4j Vulnerability?

### ISSUE THREAD

**Issue by bengroves** [plotly/dash-bio#669]
see thread [here](https://github.com/igvteam/igv/issues/1068). It appears that the vulnerability is addressed in versions > 2.11.8.

According to the [package.json](https://github.com/plotly/dash-bio/blob/1f0366394736f56c4b74fa11d8a4b00c9a32de1d/package.json#L33) and [package-info.json](https://github.com/plotly/dash-bio/blob/1f0366394736f56c4b74fa11d8a4b00c9a32de1d/dash_bio/package-info.json#L33) it looks like dash-bio uses an older version (i.e. IGV 2.6.8).

I dunno whether this is a problem...

**Comment by alexcjohnson** [comment]
It's a little confusing to be sure... but dash-bio uses the JavaScript package [igv.js](https://github.com/igvteam/igv.js), which is based on but distinct from [the original igv](https://github.com/igvteam/igv) Java application. Log4j is a Java problem and doesn't apply to JavaScript.
