### ISSUE TITLE
Can NeedlePlot be run as standalone plotly.js?

### ISSUE THREAD

**Issue by jberg1999** [plotly/dash-bio#674]
I am interested in integrating a Dash Bio NeedlePlot into a html page so that the plot can be redrawn on user input. To do this, believe that I would need to be able to call javascript code that generates the underlying plotly figure in much the same way that one might create a normal plotly.js plot. Since Dash Bio has plotly.js under the hood, is it possible to do something like this?
-Thanks

**Comment by alexcjohnson** [comment]
We don't package Dash Bio for use outside of Dash, but you're welcome to pilfer the code that calls plotly.js here: https://github.com/plotly/dash-bio/blob/master/src/lib/fragments/NeedlePlot.react.js

**Comment by jberg1999** [comment]
Thank you so much! I am not sure if I will try to replicate the Dash NeedlePlot exactly, but this code provides a nice reference in case I choose to construct my own type of plot.
