### ISSUE TITLE
jsme in callbacks

### ISSUE THREAD

**Issue by mwannier30** [plotly/dash-bio#736]
Hi, 

I'm trying to create a dash app with a dash_bio.jsme object that would allow the user to draw a molecule. Then a callback would search for the given structure (using the SMILE) in a database.
So far I've tried to do basic callbacks with a component IDs like 'children' or 'smile' but it didn't work. 
Is there another component ID that might work or is there a built in function to export the SMILE from the jsme?
Thanks!

**Comment by dtingey** [comment]
As far as I know (which is admittedly not far) you can use the 'smiles' component_property of the Jsme component as both Input and Output in callbacks:

```
app.layout = html.Div([
    dash_bio.Jsme(id="jsme-viewer"),
    html.Div(id="smiles-out")
])

@callback(
    Output(component_id='smiles-out', component_property='children'),
    Input(component_id='jsme-viewer', component_property='smiles')
)
def show_smiles(smiles_string):
    return smiles_string
```

**Comment by dtingey** [comment]
@mwannier30 You may have already found it but you can use the property 'eventSmiles' to get the smiles string stored in the Jsme viewer. This is different from the 'smiles' property, as it will update anytime a change is made in the Jsme editor.
